### ISSUE TITLE
Mencari Produk

### ISSUE THREAD

**Issue by mm0ne** [rpl-tipsen/tipsen#10]
**User Story**
Pengguna dapat mencari produk yang diinginkannya melalui search bar pada laman utama

**Acceptance Criteria**
1. Pengguna dapat mengakses search bar dengan mudah
2. Pengguna dapat menggunakan keyword yang tidak lengkap untuk mencari produknya
3. Tampilkan pesan jika produk tidak dapat ditemukan
4. Pengguna dapat mengklik salah satu entry hasil pencarian produk untuk melihat detail produk

**Tasks**
- [x] 1. Implementasi fitur search menggunakan REST API
- [x] 2. Implementasi UI untuk fitur search
- [x] 3. Integrasi backend dengan UI
- [x] 4. Handle Tampilan jika produk tidak ditemukan
- [x] 5. Link produk pada hasil pencarian ke laman detail produk
