### ISSUE TITLE
Menampilkan Daftar Produk (Admin)

### ISSUE THREAD

**Issue by swusjask** [rpl-tipsen/tipsen#11]
Sebagai seorang Admin yang telah login di Tipsen, saya ingin melihat daftar produk yang ada pada platform.

**Acceptance Criteria**:

- Saat saya membuka aplikasi dan masuk ke halaman utama, sistem menampilkan daftar produk yang tersedia.
- Saya dapat dengan mudah menavigasi daftar produk untuk melihat informasi dasar.

**Tasks**:

- [x] Desain tampilan halaman daftar produk.
- [x] Implementasi logika untuk menampilkan daftar produk dari database.
- [x] Menambahkan navigasi yang mudah untuk melihat setiap produk.
