### ISSUE TITLE
User Profile Feature

### ISSUE THREAD

**Issue by mm0ne** [rpl-tipsen/tipsen#3]
**User Story**
Pembeli bisa melihat profil data dirinya melalui laman web terpisah. Pembeli juga bisa mengatur alamat-alamat yang ia punya melalui laman ini

**Acceptance Criteria**
1. Pembeli bisa mengakses laman ini dengan mudah
2. Pembeli bisa melihat data profil dan alamat-alamatnya dengan jelas.
3. Pembeli bisa membuat, mengubah, serta menghapus alamat dengan maksimal 3 alamat per akun
4. Pada skenario CUD harus diterapkan input validasi. Jika gagal, tampilkan pesan error, sedangkan jika berhasil, tampilkan pesan success.
5. Implementasi UI pada CUD harus menerapkan state-driven yang bergantung pada status berhasil atau gagalnya sebuah aktivitas

**Tasks**
- [x] 1. Implementasi backend CRUD dalam bentuk REST API (termasuk database model definition)
- [x] 2. implementasi UI untuk laman 'profile'
- [x] 3. Integrasi UI dengan dengan backend
- [x] 4. error atau success message handling pada UI
- [x] 5. Testing Input Validation
