### ISSUE TITLE
Authentication and Registration

### ISSUE THREAD

**Issue by mm0ne** [rpl-tipsen/tipsen#6]
**User Story**
Pengguna yang ingin membeli barang harus mempunyai akun serta login ke akunnya terlebih dahulu. Admin yang ingin mengelola produk serta pesanan harus login ke akunnya yang telah dibuat. 

**Acceptance Criteria**
1. Laman harus bisa diakses dengan mudah
2. Form harus jelas dengan input validation
3. status error atau success harus ditampilkan dengan jelas
4. Pembeli bisa registrasi dengan mudah
5. Pembeli atau admin yang telah login tidak bisa mengakses laman ini
6. Pengguna harus bisa logout

**Tasks**
- [x] 1. Implementasi logic pembuatan akun baru 
- [x] 2. Implementasi login dan logout dengan django auth
- [x] 3. Implementasi UI laman login, registrasi, serta logout
- [x] 4. Integrasi backend dengan UI
- [x] 5. Implementasi UI untuk state logged-in atau logged-out
- [x] 6. Implementasikan UI untuk notifikasi error atau success pada aktivitas CUD
