### ISSUE TITLE
Memesan Produk

### ISSUE THREAD

**Issue by NeoZap** [rpl-tipsen/tipsen#9]
**User Story:**
Sebagai seorang Pembeli yang menggunakan Tipsen, saya ingin dapat memesan produk yang tersedia melalui aplikasi agar saya bisa melakukan pemesanan produk dengan mudah dan nyaman.

**Acceptance Criteria:**
- Ketika pengguna menekan tombol "Pesan Sekarang" pada detail produk, sistem harus menampilkan formulir untuk memasukkan jumlah yang diinginkan dan alamat pengiriman.
- Setelah pengguna mengisi jumlah pesanan dan alamat pengiriman, sistem harus menghitung total biaya yang harus dibayarkan.
- Sistem harus menampilkan daftar rekening pembayaran, total biaya, dan form pembayaran yang dapat diisi oleh pengguna.
- Pengguna harus dapat memberikan nomor referensi dan metode pembayaran yang nantinya akan digunakan oleh Admin untuk verifikasi pembayaran.
- Setelah pembayaran selesai, pengguna harus dapat menekan tombol "Selesai" untuk mengirimkan data kepada sistem.
- Sistem harus menyimpan data pemesanan dengan status "menunggu verifikasi" setelah pengguna menekan tombol "Selesai".
- Pengguna harus diarahkan ke laman "pesanan saya" agar dapat melihat pesanannya setelah melakukan pemesanan.
- Sistem harus menampilkan notifikasi gagal apabila terjadi kegagalan dalam pengiriman data ke sistem maupun penyimpanan data.

**Tasks:**
- [x] Implementasi halaman formulir untuk memasukkan jumlah pesanan dan alamat pengiriman setelah pengguna menekan tombol "Pesan Sekarang".
- [x] Menghitung total biaya berdasarkan jumlah pesanan yang dimasukkan oleh pengguna.
- [x] Tampilkan daftar rekening pembayaran, total biaya, dan form pembayaran yang dapat diisi oleh pengguna.
- [x] Simpan data pemesanan dengan status "menunggu verifikasi" setelah pembayaran selesai.
- [x] Tampilkan notifikasi gagal yang jelas apabila terjadi kegagalan dalam pengiriman data ke sistem maupun penyimpanan data.
- [x] Navigasi otomatis ke laman "pesanan saya" setelah pengguna menekan tombol "Selesai".
